### ISSUE TITLE
Regarding the No-Focus issue 

### ISSUE THREAD

**Issue by migo77** [reblws/tab-search#21] opened 2017-11-15 17:47 UTC
Hello,

I'm M.Samuel who reported about the flashing cursor not focused in the search box. I'm on Firefox v57 (Quantum) which was released just yesterday and it's a fresh clean install in a Windows 7 x64. I started to believe it's not related to the extension because the "LastPass" extension doesn't have focus too. I think it may be related to a browser bug. I'm not sure though.

Many thanks for your efforts.

**Comment by reblws** [comment] 2017-11-15 18:07
Duplicate of #13

**Closed** 2017-11-15 18:07 UTC
