### ISSUE TITLE
Change main Keyboard Shortcut

### ISSUE THREAD

**Issue by obriat** [reblws/tab-search#67] opened 2018-10-18 12:45 UTC
Ctrl + shift + F overlaps "Panorama view" extension own shortcut.

It should be possible to change it in the extension settings page, that also a good place to to learn it, since this info is only available on the extension web page.

**Comment by tolgacanatan** [comment] 2018-11-14 08:07
It is really hard to press 'ctrl + shift + f'. We should be able to change this shortcut.

**Comment by tg-x** [comment] 2019-01-04 18:19
this is a duplicate of #2

**Closed** 2022-05-17 23:56 UTC
Labels: duplicate
